filesize_format = "B" # can be b, kb, kib, mb, mib, gb, gib, etc
filesize_metric = true # true => (KB, MB, GB), false => (KiB, MiB, GiB)
skip_welcome_message = true # Note to nushell developer: This is expected to be false, when testing nushell itself
disable_table_indexes = false
nonzero_exit_errors = true

startup = [
  "def prompt-pre-cmd [] { echo [(ansi -o '0') (pwd) (char bel)] | str collect }",
  "alias la = ls -la",
  "alias ll = ls -l",
  "mkdir ~/.cache/starship", "starship init nu | save ~/.cache/starship/init.nu", "source ~/.cache/starship/init.nu",
  "zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu",
  "fnm env --shell bash | lines | str substring '7,' | split column '=' name value | str trim -c '\"' | where name != PATH | load-env",
  "pathvar add (fnm env --shell bash | lines | str substring '7,' | split column '=' name value | where name == PATH | get value | split column ':' path | str trim -c '\"' | get path)",
  "let-env PROMPT_COMMAND = $'prompt-pre-cmd;($nu.env.PROMPT_COMMAND)'",
  "let-env LS_COLORS = (vivid generate molokai | first)"
]
prompt = "starship_prompt"

table_mode = "rounded"
pivot_mode = "auto" # auto, always, never
ctrlc_exit = false
complete_from_path = true
rm_always_trash = true

[color_config]
primitive_int = "green"
primitive_decimal = "red"
primitive_filesize = "ur"
primitive_string = "pb"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "green"
primitive_date = "ru"
primitive_duration = "blue"
primitive_range = "purple"
primitive_path = "yellow"
primitive_binary = "cyan"
separator_color = "purple"
header_align = "l" # left|l, right|r, center|c
header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
index_color = "rd"
leading_trailing_space_bg = "white"

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive" # alwaysadd,ignoreconsecutive
history_ignore_space = false
completion_type = "fuzzy" # circular, list, fuzzy
completion_prompt_limit = 100
completion_match_method = "case-insensitive"
keyseq_timeout_ms = 500 # ms
edit_mode = "vi" # vi, emacs
auto_add_history = true
bell_style = "audible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
tab_stop = 2

[textview]
term_width = "default" # "default" or a number
tab_width = 2
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping" # Character, NoWrapping
use_italics = true
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
pager = "less"
theme = "TwoDark"

path = [
  "~/bin",
  "~/.local/bin",
  "~/.cargo/bin",
  "/usr/local/sbin",
  "/usr/local/bin",
  "/usr/sbin",
  "/usr/bin",
  "/sbin",
  "/bin",
  "/snap/bin",
  "~/.fzf/bin"
]

[env]
FZF_BASE = "~/.fzf"
FZF_DEFAULT_COMMAND = "rg --files --hidden --glob \"!.git/*\""
FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1
VISUAL="nvim"
EDITOR="nvim"
USE_EDITOR="nvim"
